version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: attendance-web:latest
    command: >
      gunicorn attendanceArc.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --worker-class gthread
      --threads 4
      --timeout 120
      --log-level info
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - .:/app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  sqlite_volume:
